# Generated by Django 2.1.3 on 2018-12-11 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='codigo')),
                ('turma', models.CharField(max_length=100, verbose_name='Turma')),
                ('postura_profissional_media', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Média da Postura Profissional')),
                ('postura_profissional_dp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desvio Padrão da Postura Profissional do docente')),
                ('atuacao_profissional_media', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Média da Atuacação Profissional do docente')),
                ('atuacao_profissional_dp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desvio Padrão da Atuação Profissional do docente')),
                ('autoavaliacao_aluno_media', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Média da Postura Profissional do docente')),
                ('autoavaliacao_aluno_dp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desvio Padrão da Postura Profissional')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ('codigo', 'turma'),
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='codigo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ('nome', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='codigo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ('nome', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='codigo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ('departamento', 'nome', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('vinculo', models.CharField(max_length=100, verbose_name='Vínculo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ('nome', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='codigo')),
                ('qnt_discentes', models.IntegerField(verbose_name='Quantidade de Discentes')),
                ('taxa_aprovacao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de Aprovação')),
                ('media_turma', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Média da Turma')),
                ('qnt_aprovados_primeira', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade de Aprovados na primeira vez que pagou')),
                ('evasao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade de Trancamentos')),
                ('autoavaliacao_aluno_media', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Média da Postura Profissional do docente')),
                ('autoavaliacao_aluno_dp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desvio Padrão da Postura Profissional')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Disciplina', verbose_name='Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ('disciplina', 'codigo'),
            },
        ),
    ]
