# Generated by Django 2.1.3 on 2018-12-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(default='AAA123', max_length=200, verbose_name='codigo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='departamento',
            field=models.CharField(max_length=200, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
