# Generated by Django 2.1.3 on 2018-12-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='qnt_discentes',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Discentes'),
            preserve_default=False,
        ),
    ]
