# Generated by Django 2.1.3 on 2018-12-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.IntegerField(unique=True, verbose_name='codigo'),
        ),
    ]
