# Generated by Django 2.1.3 on 2018-12-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181213_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='autoavaliacao_aluno_dp',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='autoavaliacao_aluno_media',
        ),
        migrations.AddField(
            model_name='curso',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Departamento', verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='anoperiodo',
            field=models.CharField(default='None', max_length=10, verbose_name='Ano/Periodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='media_faltas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Média da Faltas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='qnt_aprovados',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Aprovados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='qnt_reposicao',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Reposições'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='qnt_reprovados',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Reprovados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='qnt_trancamentos',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Trancamentos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='taxa_reprovacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de Reprovação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='autoavaliacao_aluno_dp',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desvio Padrão da Autoavaliação do Discente'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='autoavaliacao_aluno_media',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Média da Autoavaliação do Discente'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='qnt_aprovados_primeira',
            field=models.IntegerField(verbose_name='Quantidade de Aprovados na primeira vez que pagou'),
        ),
    ]
