# Generated by Django 2.1.3 on 2018-12-31 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181224_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='qnt_reprovados',
            new_name='qnt_reprovacao',
        ),
    ]
