# Generated by Django 2.1.3 on 2018-12-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181218_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='id_componente',
            field=models.IntegerField(unique=True, verbose_name='id_componente'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='codigo',
            field=models.IntegerField(unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Disciplina', to_field='id_componente', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Professor', to_field='codigo', verbose_name='Professor'),
        ),
    ]
